slug: esp
visit: visitnumber
charts:
- chart: sex
  title: Sex
- chart: race
  title: Race
- chart: subjectrole
  title: Role
webservers:
  - name: production
    url: https://sleepdata.org
  - name: staging
    url: https://staging.partners.org/sleepdata.org
